# ./.tmuxinator.yml
name: project
startup_window: scrivitore
windows:
  - scrivitore:
      panes:
        - nvim
  - run_baby_run:
      panes:
        - 
  - guardatore:
      layout: vertical
      panes:
        - htop
        - nvtop
    
