# ./.tmuxinator.yml
name: <%= @args[0] %>
startup_window: scrivitore
windows:
  - scrivitore:
      panes:
        - vim
  - run_baby_run:
      panes:
        - 
  - guardatore:
      layout: vertical
      panes:
        - htop
        - nvtop
    
