# ./.tmuxinator.yml
name: project
startup_window: editor
windows:
  - scrivitore:
      panes:
        - nvim
  - run_baby_run:
      layout: main-vertical
      panes:
        - 
        - htop
        - watch -n1 nvidia-smi
    
