# ./.tmuxinator.yml
name: project
startup_window: editor
windows:
  - scrivitore:
      panes:
        - nvim
  - run_baby_run:
      layout: main-vertical
      panes:
        - 
  - guardatore:
      panes:
        - htop
        - nvtop
    
